apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: book-app-ingress
spec:
  ingressClassName: public
  rules:
    - host: bookapp.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3200        
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000

